os: linux
language: python
dist: xenial

jobs:
  include:
    - name: ROS tests
      #
      # The following was taken from here
      # https://github.com/ros-industrial/industrial_ci/tree/master#id4
      #
      sudo: required
      services:
        - docker
      env:
        - ROS_DISTRO="melodic"
        - BEFORE_SETUP_TARGET_WORKSPACE="pip install coverage"
        - DOCKER_RUN_OPTS="-e COVERAGE_RC_FILE=/root/target_ws/src/ros_ci_and_coverage/.coveragerc -e COVERAGE_PROCESS_START=.coveragerc -e CODECOV_TOKEN=$CODECOV_TOKEN"
        - AFTER_BUILD_TARGET_WORKSPACE="ls -a /root/.ros"
        - AFTER_AFTER_RUN_TARGET_TEST="coverage combine /root/.ros/ && coverage xml && bash <(curl -s https://codecov.io/bash)"
      install:
        - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
      script:
        - .industrial_ci/travis.sh
