os: linux
language: python
dist: xenial

jobs:
  include:
    - name: ROS tests
      #
      # The following was taken from here
      # https://github.com/ros-industrial/industrial_ci/tree/master#id4
      #
      sudo: required
      services:
        - docker
      env:
        - ADDITIONAL_DEBS="curl"
        - ROS_DISTRO="melodic"
        - BEFORE_SETUP_TARGET_WORKSPACE="pip install coverage"
        - CI_ENV="bash <(curl -s https://codecov.io/env)"
        - DOCKER_RUN_OPTS="-e TRAVIS_COMMIT=$TRAVIS_COMMIT -e COVERAGE_RCFILE=/root/target_ws/src/ros_ci_and_coverage/.coveragerc -e COVERAGE_PROCESS_START=.coveragerc -e CODECOV_TOKEN=$CODECOV_TOKEN"
        - AFTER_RUN_TARGET_TEST="ls -a /root/.ros/"
        - AFTER_AFTER_RUN_TARGET_TEST="cd /root/.ros && coverage combine && coverage xml"
        - AFTER_AFTER_AFTER_RUN_TARGET_TEST="bash <(curl -s https://codecov.io/bash) -v -s /root/.ros -C $TRAVIS_COMMIT"
      install:
        - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
      script:
        - .industrial_ci/travis.sh
