os: linux
language: python
dist: xenial

jobs:
  include:
    - name: ROS tests
      #
      # The following was taken from here
      # https://github.com/ros-industrial/industrial_ci/tree/master#id4
      #
      sudo: required
      services:
        - docker
      env:
        - ROS_DISTRO="melodic"
        - TARGET_WORKSPACE="no_real_ws"
      install:
        - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
      script:
        - .industrial_ci/travis.sh
