os: linux
language: python
dist: xenial

jobs:
  include:
    - name: ROS tests
      #
      # The following was taken from here
      # https://github.com/ros-industrial/industrial_ci/tree/master#id4
      #
      sudo: required
      services:
        - docker
      env:
        - ADDITIONAL_DEBS="curl"
        - ROS_DISTRO="melodic"
        - UPSTREAM_WORKSPACE="upstream.repos"
        # Build with coverage on, debug required for proper information in C++
        - CMAKE_ARGS="-DENABLE_COVERAGE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug""
        # List of packages to generate coverage reports
        - DOCKER_RUN_OPTS='-e COVERAGE_PKGS="example_pkg"'
        # Run coverage testing
        - AFTER_SCRIPT="./.coverage.sh"
      install:
        - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
      script:
        - source ./.codecov.sh && .industrial_ci/travis.sh
